// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BookingStatus string

const (
	BookingStatusActive        BookingStatus = "active"
	BookingStatusCancelled     BookingStatus = "cancelled"
	BookingStatusLateCancel    BookingStatus = "late_cancel"
	BookingStatusClubCancelled BookingStatus = "club_cancelled"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type RouteType string

const (
	RouteTypeNovice      RouteType = "novice"
	RouteTypeExperienced RouteType = "experienced"
)

func (e *RouteType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RouteType(s)
	case string:
		*e = RouteType(s)
	default:
		return fmt.Errorf("unsupported scan type for RouteType: %T", src)
	}
	return nil
}

type NullRouteType struct {
	RouteType RouteType `json:"route_type"`
	Valid     bool      `json:"valid"` // Valid is true if RouteType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRouteType) Scan(value interface{}) error {
	if value == nil {
		ns.RouteType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RouteType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRouteType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RouteType), nil
}

type SlotStatus string

const (
	SlotStatusScheduled SlotStatus = "scheduled"
	SlotStatusCancelled SlotStatus = "cancelled"
)

func (e *SlotStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SlotStatus(s)
	case string:
		*e = SlotStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SlotStatus: %T", src)
	}
	return nil
}

type NullSlotStatus struct {
	SlotStatus SlotStatus `json:"slot_status"`
	Valid      bool       `json:"valid"` // Valid is true if SlotStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSlotStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SlotStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SlotStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSlotStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SlotStatus), nil
}

type Booking struct {
	ID          pgtype.UUID        `json:"id"`
	SlotID      pgtype.UUID        `json:"slot_id"`
	ClientID    pgtype.UUID        `json:"client_id"`
	SeatsCount  int32              `json:"seats_count"`
	RentalCount int32              `json:"rental_count"`
	Status      BookingStatus      `json:"status"`
	PriceTotal  pgtype.Numeric     `json:"price_total"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
}

type Client struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Instructor struct {
	ID     pgtype.UUID    `json:"id"`
	Name   string         `json:"name"`
	Rating pgtype.Numeric `json:"rating"`
}

type Rating struct {
	ID           pgtype.UUID        `json:"id"`
	BookingID    pgtype.UUID        `json:"booking_id"`
	InstructorID pgtype.UUID        `json:"instructor_id"`
	Rating       int32              `json:"rating"`
	Comment      pgtype.Text        `json:"comment"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Route struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Type        RouteType   `json:"type"`
	CapacityCap int32       `json:"capacity_cap"`
	DurationMin int32       `json:"duration_min"`
	Geometry    string      `json:"geometry"`
}

type Slot struct {
	ID               pgtype.UUID        `json:"id"`
	RouteID          pgtype.UUID        `json:"route_id"`
	InstructorID     pgtype.UUID        `json:"instructor_id"`
	StartAt          pgtype.Timestamptz `json:"start_at"`
	TotalSeats       int32              `json:"total_seats"`
	FreeSeats        int32              `json:"free_seats"`
	FreeRentalBoards int32              `json:"free_rental_boards"`
	Price            pgtype.Numeric     `json:"price"`
	RentalPrice      pgtype.Numeric     `json:"rental_price"`
	MeetingPoint     string             `json:"meeting_point"`
	MeetingPointLat  float64            `json:"meeting_point_lat"`
	MeetingPointLng  float64            `json:"meeting_point_lng"`
	Status           SlotStatus         `json:"status"`
}
