// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BookingStatus string

const (
	BookingStatusActive             BookingStatus = "ACTIVE"
	BookingStatusCancelledByClient  BookingStatus = "CANCELLED_BY_CLIENT"
	BookingStatusCancelledByCenter  BookingStatus = "CANCELLED_BY_CENTER"
	BookingStatusCompleted          BookingStatus = "COMPLETED"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"`
}

func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type GearType string

const (
	GearTypeOwn    GearType = "OWN"
	GearTypeRental GearType = "RENTAL"
)

func (e *GearType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GearType(s)
	case string:
		*e = GearType(s)
	default:
		return fmt.Errorf("unsupported scan type for GearType: %T", src)
	}
	return nil
}

type TrackConfig string

const (
	TrackConfigShort TrackConfig = "SHORT"
	TrackConfigLong  TrackConfig = "LONG"
)

func (e *TrackConfig) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackConfig(s)
	case string:
		*e = TrackConfig(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackConfig: %T", src)
	}
	return nil
}

type SlotStatus string

const (
	SlotStatusScheduled          SlotStatus = "SCHEDULED"
	SlotStatusCancelledByWeather SlotStatus = "CANCELLED_BY_WEATHER"
	SlotStatusCompleted          SlotStatus = "COMPLETED"
)

func (e *SlotStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SlotStatus(s)
	case string:
		*e = SlotStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SlotStatus: %T", src)
	}
	return nil
}

type Booking struct {
	ID                  pgtype.UUID        `json:"id"`
	SlotID              pgtype.UUID        `json:"slot_id"`
	ClientID            pgtype.UUID        `json:"client_id"`
	GearType            GearType           `json:"gear_type"`
	Status              BookingStatus      `json:"status"`
	CancellationReason  pgtype.Text        `json:"cancellation_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
}

type Client struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	IsRegular bool               `json:"is_regular"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Marshal struct {
	ID        pgtype.UUID    `json:"id"`
	Name      string         `json:"name"`
	AvatarUrl string         `json:"avatar_url"`
	Rating    pgtype.Numeric `json:"rating"`
}

type Rating struct {
	ID        pgtype.UUID        `json:"id"`
	BookingID pgtype.UUID        `json:"booking_id"`
	MarshalID pgtype.UUID        `json:"marshal_id"`
	Rating    int32              `json:"rating"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Slot struct {
	ID              pgtype.UUID    `json:"id"`
	MarshalID       pgtype.UUID    `json:"marshal_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	TrackConfig     TrackConfig    `json:"track_config"`
	MaxKarts        int32          `json:"max_karts"`
	AvailableKarts  int32          `json:"available_karts"`
	RentalTariff    int32          `json:"rental_tariff"`
	GatheringPlace  string         `json:"gathering_place"`
	Status          SlotStatus     `json:"status"`
}
