// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ---------- CreateClient ----------

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, phone)
VALUES ($1, $2)
RETURNING id, name, phone, is_regular, created_at
`

type CreateClientParams struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.Name, arg.Phone)
	var i Client
	err := row.Scan(&i.ID, &i.Name, &i.Phone, &i.IsRegular, &i.CreatedAt)
	return i, err
}

// ---------- GetClientByPhone / GetClientByID ----------

const getClientByPhone = `-- name: GetClientByPhone :one
SELECT id, name, phone, is_regular, created_at FROM clients
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetClientByPhone(ctx context.Context, phone string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByPhone, phone)
	var i Client
	err := row.Scan(&i.ID, &i.Name, &i.Phone, &i.IsRegular, &i.CreatedAt)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, phone, is_regular, created_at FROM clients
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClientByID(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(&i.ID, &i.Name, &i.Phone, &i.IsRegular, &i.CreatedAt)
	return i, err
}

// ---------- ListSlots / GetSlotByID ----------
// Both return the slot joined with its marshal, matching the nested `Marshal`
// object the client expects inside `Slot` per openapi.yaml.

type ListSlotsParams struct {
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

type ListSlotsRow struct {
	ID               pgtype.UUID        `json:"id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	TrackConfig      TrackConfig        `json:"track_config"`
	MaxKarts         int32              `json:"max_karts"`
	AvailableKarts   int32              `json:"available_karts"`
	RentalTariff     int32              `json:"rental_tariff"`
	GatheringPlace   string             `json:"gathering_place"`
	Status           SlotStatus         `json:"status"`
	MarshalID        pgtype.UUID        `json:"marshal_id"`
	MarshalName      string             `json:"marshal_name"`
	MarshalAvatarUrl string             `json:"marshal_avatar_url"`
	MarshalRating    pgtype.Numeric     `json:"marshal_rating"`
}

const listSlots = `-- name: ListSlots :many
SELECT s.id, s.start_time, s.track_config, s.max_karts, s.available_karts,
       s.rental_tariff, s.gathering_place, s.status,
       m.id AS marshal_id, m.name AS marshal_name, m.avatar_url AS marshal_avatar_url, m.rating AS marshal_rating
FROM slots s
JOIN marshals m ON s.marshal_id = m.id
WHERE s.start_time >= $1 AND s.start_time <= $2
ORDER BY s.start_time ASC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListSlots(ctx context.Context, arg ListSlotsParams) ([]ListSlotsRow, error) {
	rows, err := q.db.Query(ctx, listSlots, arg.StartTime, arg.StartTime_2, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlotsRow
	for rows.Next() {
		var i ListSlotsRow
		if err := rows.Scan(
			&i.ID, &i.StartTime, &i.TrackConfig, &i.MaxKarts, &i.AvailableKarts,
			&i.RentalTariff, &i.GatheringPlace, &i.Status,
			&i.MarshalID, &i.MarshalName, &i.MarshalAvatarUrl, &i.MarshalRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type GetSlotByIDRow = ListSlotsRow

const getSlotByID = `-- name: GetSlotByID :one
SELECT s.id, s.start_time, s.track_config, s.max_karts, s.available_karts,
       s.rental_tariff, s.gathering_place, s.status,
       m.id AS marshal_id, m.name AS marshal_name, m.avatar_url AS marshal_avatar_url, m.rating AS marshal_rating
FROM slots s
JOIN marshals m ON s.marshal_id = m.id
WHERE s.id = $1 LIMIT 1
`

func (q *Queries) GetSlotByID(ctx context.Context, id pgtype.UUID) (GetSlotByIDRow, error) {
	row := q.db.QueryRow(ctx, getSlotByID, id)
	var i GetSlotByIDRow
	err := row.Scan(
		&i.ID, &i.StartTime, &i.TrackConfig, &i.MaxKarts, &i.AvailableKarts,
		&i.RentalTariff, &i.GatheringPlace, &i.Status,
		&i.MarshalID, &i.MarshalName, &i.MarshalAvatarUrl, &i.MarshalRating,
	)
	return i, err
}

// ---------- Bookings ----------

type CreateBookingParams struct {
	SlotID   pgtype.UUID `json:"slot_id"`
	ClientID pgtype.UUID `json:"client_id"`
	GearType GearType    `json:"gear_type"`
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (slot_id, client_id, gear_type)
VALUES ($1, $2, $3)
RETURNING id, slot_id, client_id, gear_type, status, cancellation_reason, created_at, cancelled_at
`

// The claim_kart_on_booking trigger (see db_init.sql) enforces BR-01 and raises
// a Postgres exception (NO_KARTS_AVAILABLE / SLOT_GONE) instead of silently
// overselling — the handler maps those errors to 409/410.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.SlotID, arg.ClientID, arg.GearType)
	var i Booking
	err := row.Scan(
		&i.ID, &i.SlotID, &i.ClientID, &i.GearType, &i.Status,
		&i.CancellationReason, &i.CreatedAt, &i.CancelledAt,
	)
	return i, err
}

type UpdateBookingStatusParams struct {
	ID                 pgtype.UUID   `json:"id"`
	Status             BookingStatus `json:"status"`
	CancellationReason pgtype.Text   `json:"cancellation_reason"`
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET status = $2,
    cancellation_reason = COALESCE($3, cancellation_reason),
    cancelled_at = CASE WHEN $2 IN ('CANCELLED_BY_CLIENT', 'CANCELLED_BY_CENTER') THEN NOW() ELSE cancelled_at END
WHERE id = $1
RETURNING id, slot_id, client_id, gear_type, status, cancellation_reason, created_at, cancelled_at
`

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status, arg.CancellationReason)
	var i Booking
	err := row.Scan(
		&i.ID, &i.SlotID, &i.ClientID, &i.GearType, &i.Status,
		&i.CancellationReason, &i.CreatedAt, &i.CancelledAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, slot_id, client_id, gear_type, status, cancellation_reason, created_at, cancelled_at FROM bookings
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID, &i.SlotID, &i.ClientID, &i.GearType, &i.Status,
		&i.CancellationReason, &i.CreatedAt, &i.CancelledAt,
	)
	return i, err
}

type ListBookingsByClientParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

const listBookingsByClient = `-- name: ListBookingsByClient :many
SELECT b.id, b.slot_id, b.client_id, b.gear_type, b.status, b.cancellation_reason, b.created_at, b.cancelled_at FROM bookings b
JOIN slots s ON b.slot_id = s.id
WHERE b.client_id = $1
ORDER BY s.start_time DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListBookingsByClient(ctx context.Context, arg ListBookingsByClientParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByClient, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID, &i.SlotID, &i.ClientID, &i.GearType, &i.Status,
			&i.CancellationReason, &i.CreatedAt, &i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------- Ratings ----------

type CreateRatingParams struct {
	BookingID pgtype.UUID `json:"booking_id"`
	MarshalID pgtype.UUID `json:"marshal_id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
}

const createRating = `-- name: CreateRating :one
INSERT INTO ratings (booking_id, marshal_id, rating, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, booking_id, marshal_id, rating, comment, created_at
`

func (q *Queries) CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, createRating, arg.BookingID, arg.MarshalID, arg.Rating, arg.Comment)
	var i Rating
	err := row.Scan(&i.ID, &i.BookingID, &i.MarshalID, &i.Rating, &i.Comment, &i.CreatedAt)
	return i, err
}
