name: apex_mobile
description: "Apex Karting Center Booking App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management & DI
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  
  # Navigation
  go_router: ^14.1.4
  
  # Networking & API
  dio: ^5.4.3
  
  # Storage
  flutter_secure_storage: ^9.2.1
  shared_preferences: ^2.2.3
  
  # UI Kit & Utils
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
